# Generated by Django 3.0 on 2021-08-15 16:34

"""After code refactoring:
- Step 1:  let Django generate automatically migration files
- Step 2: Generated manually
+ Replace migrations.CreateModel(...) by migrations.SeparateDatabaseAndState()
+ Put migrations.CreateModel(...) in state_operations and in add database_operations=[]
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                          verbose_name='ID')),
                        ('favorite_city', models.CharField(blank=True, max_length=64)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                      to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
            # Table already exists. See  oc_lettings_site/migrations/0003_auto_20210815_1634.py
            database_operations=[],
        ),
    ]
