version: 2.1

orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@1.2.6

executors:
  docker-executor:
    environment:
      IMAGE_NAME: oc-lettings-site
    docker:
      - image: cimg/python:3.8

jobs:
  complite-and-test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Create venv
          command: python -m venv venv
      - run:
          name: Activate venv
          command: source venv/bin/activate
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Check PEP8
          command: flake8
      - run:
          name: Run tests
          env:
            SECRET_KEY: $SECRET_KEY
            DSN_SENTRY: $DSN_SENTRY
          command: pytest

  dockerize:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1 .

  publish-docker-image-to-dockerhub:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
            docker logout

  deploy-to-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku container:login
      - run: heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
      - run: heroku config:set DSN_SENTRY=$DSN_SENTRY -a $HEROKU_APP_NAME
      - run: heroku config:set ALLOWED_HOSTS=$ALLOWED_HOSTS -a $HEROKU_APP_NAME
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          force: true
#      - run: heroku config:set DEBUG_COLLECTSTATIC=1 -a oc-lettings-7
#      - run: heroku config:set DISABLE_COLLECTSTATIC=1 -a oc-lettings-7
#      - run: heroku restart -a oc-lettings-7
#        - run : docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
#      - heroku/push-docker-image:
#          process-types: web
#      - heroku/release-docker-image:
#          process-types: web

workflows:
  build-test-deploy:
    jobs:
      - complite-and-test
      - dockerize:
          requires:
            - complite-and-test
          filters: # Only dockerize from main branch
            branches:
              only: main
      - publish-docker-image-to-dockerhub:
          requires:
            - dockerize
      - deploy-to-heroku:
          requires:
            - publish-docker-image-to-dockerhub
          filters: # Only deploy from main branch
            branches:
              only: main