jobs:
  build_and_test:
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker:
          version: 19.03.13
      # build
      - checkout
      - run: docker build -t $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 .
      # test
      - run:
          name: Run tests
#          env:
          environment:
            SECRET_KEY: $SECRET_KEY
            DSN_SENTRY: $DSN_SENTRY
#          env:
#            SECRET_KEY: $SECRET_KEY
          command: docker run $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 pytest
#          command: |
#            echo SECRET_KEY
#            echo DSN_SENTRY
#            docker run $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 pytest
  build_and_deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker:
          version: 19.03.13
      # build
      - checkout
      - run: docker build .
      # deploy
      - heroku/install
      - run: heroku container:login
      - run: heroku config:set SECRET_KEY=$SECRET_KEY -a oc-lettings-7
      - run: heroku config:set DSN_SENTRY=$DSN_SENTRY -a oc-lettings-7
      - run: heroku config:set ALLOWED_HOSTS=$ALLOWED_HOSTS -a oc-lettings-7
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web
orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@1.2.6
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - build_and_test
      - build_and_deploy:
          requires:
            - build_and_test
