jobs:
  build_and_test:
    environment:
      IMAGE_NAME: oc-lettings-site
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker:
          version: 19.03.13
      # build
      - checkout
      - run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: check PEP8
          command: docker run $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1 flake8
      # test
      - run:
          name: Run tests
#          env:
          environment:
            SECRET_KEY: $SECRET_KEY
            DSN_SENTRY: $DSN_SENTRY
#          env:
#            SECRET_KEY: $SECRET_KEY
          command: docker run $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 pytest
#          command: |
#            echo SECRET_KEY
#            echo DSN_SENTRY
#            docker run $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 pytest

  publish-on-dockerhub:
    environment:
      IMAGE_NAME: oc-lettings-site
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
            docker logout
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1

  build_and_deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker:
          version: 19.03.13
      # build
      - checkout
      - run: docker build .
      # deploy
      - heroku/install
      - run: heroku container:login
      - run: heroku config:set SECRET_KEY=$SECRET_KEY -a oc-lettings-7
      - run: heroku config:set DSN_SENTRY=$DSN_SENTRY -a oc-lettings-7
      - run: heroku config:set ALLOWED_HOSTS=$ALLOWED_HOSTS -a oc-lettings-7
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web
orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@1.2.6
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - build_and_test
      - publish-on-dockerhub:
          requires:
            - build_and_test
      - build_and_deploy:
          requires:
            - publish-on-dockerhub
